In [4]:
import pandas as pd

In [5]:
ventes = pd.read_json("ventes.json")

In [44]:
ventes.info()
ventes.head()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_commande    8 non-null      int64
 1   client         8 non-null      object
 2   produit        8 non-null      object
 3   quantite       8 non-null      int64
 4   prix_unitaire  8 non-null      float64
 5   date_commande  8 non-null      int64
 6   livree         8 non-null      bool
dtypes: bool(1), float64(1), int64(3), object(2)
memory usage: 456.0+ bytes

,id_commande,client,produit,quantite,prix_unitaire,date_commande,livree
0,1001,Alice,PC,1,999.99,1736467200000,True
1,1002,Bob,Souris,2,19.90,1736640000000,True
2,1003,Charlie,Clavier,1,49.90,1736899200000,False
3,1004,Alice,Écran,2,199.99,1737158400000,True
4,1005,David,PC,3,999.99,1737331200000,False

In [45]:
employes = pd.read_parquet("employes.parquet")

In [60]:
employes

   id_employe      nom       service  salaire  anciennete  temps_plein
0           1   Martin  Informatique    32000           5         True
1           2   Durand            RH    28000           2         True
2           3    Petit       Finance    41000          12        False
3           4   Robert     Marketing    36000           7         True
4           5  Bernard            RH    29500           1        False
5           6   Thomas  Informatique    38500           9         True

In [90]:
ventes.shape

(8, 7)

In [89]:
ventes.shape[0]

8

In [58]:
employes.shape

(6, 6)

In [92]:
ventes.dtypes

id_commande        int64
client            object
produit           object
quantite           int64
prix_unitaire    float64
date_commande      int64
livree              bool
dtype: object

In [62]:
employes.dtypes

id_employe      int64
nom            object
service        object
salaire         int64
anciennete      int64
temps_plein      bool
dtype: object

In [50]:
ventes.describe()

       id_commande  quantite  prix_unitaire  date_commande
count      8.00000  8.000000       8.000000   8.000000e+00
mean    1004.50000  1.875000     324.945000   1.737212e+12
std        2.44949  1.125992     422.069394   5.344792e+08
min     1001.00000  1.000000      19.900000   1.736467e+12
25%     1002.75000  1.000000      49.900000   1.736834e+12
50%     1004.50000  1.500000     139.945000   1.737245e+12
75%     1006.25000  2.250000     399.990000   1.737504e+12
max     1008.00000  4.000000     999.990000   1.738022e+12

In [51]:
employes.describe()

       id_employe       salaire  anciennete
count    6.000000      6.000000    6.000000
mean     3.500000  34166.666667    6.000000
std      1.870829   5163.977795    4.195235
min      1.000000  28000.000000    1.000000
25%      2.250000  30125.000000    2.750000
50%      3.500000  34000.000000    6.000000
75%      4.750000  37875.000000    8.500000
max      6.000000  41000.000000   12.000000

In [63]:
ventes.head(5)

,id_commande,client,produit,quantite,prix_unitaire,date_commande,livree
0,1001,Alice,PC,1,999.99,1736467200000,True
1,1002,Bob,Souris,2,19.90,1736640000000,True
2,1003,Charlie,Clavier,1,49.90,1736899200000,False
3,1004,Alice,Écran,2,199.99,1737158400000,True
4,1005,David,PC,3,999.99,1737331200000,False

In [66]:
ventes.tail(3)

   id_commande client  produit  quantite  prix_unitaire  date_commande  livree
5         1006   Emma   Casque         1          79.90  1737417600000    True
6         1007    Bob    Écran         1         199.99  1737763200000    True
7         1008  Lucas  Clavier         4          49.90  1738022400000   False

In [68]:
ventes.sample(1)

,id_commande,client,produit,quantite,prix_unitaire,date_commande,livree
2,1003,Charlie,Clavier,1,49.9,1736899200000,False

In [82]:
ventes.count(0)

id_commande      8
client           8
produit          8
quantite         8
prix_unitaire    8
date_commande    8
livree           8
dtype: int64

In [85]:
ventes.columns

Index(['id_commande', 'client', 'produit', 'quantite', 'prix_unitaire',
       'date_commande', 'livree'],
      dtype='object')

In [94]:
ventes

,id_commande,client,produit,quantite,prix_unitaire,date_commande,livree
0,1001,Alice,PC,1,999.99,1736467200000,True
1,1002,Bob,Souris,2,19.90,1736640000000,True
2,1003,Charlie,Clavier,1,49.90,1736899200000,False
3,1004,Alice,Écran,2,199.99,1737158400000,True
4,1005,David,PC,3,999.99,1737331200000,False
5,1006,Emma,Casque,1,79.90,1737417600000,True
6,1007,Bob,Écran,1,199.99,1737763200000,True
7,1008,Lucas,Clavier,4,49.90,1738022400000,False

In [97]:
ventes.client

0      Alice
1        Bob
2    Charlie
3      Alice
4      David
5       Emma
6        Bob
7      Lucas
Name: client, dtype: object

In [102]:
ventes.produit

0         PC
1     Souris
2    Clavier
3      Écran
4         PC
5     Casque
6      Écran
7    Clavier
Name: produit, dtype: object

In [111]:
ventes[["client","produit","quantite"]]

    client  produit  quantite
0    Alice       PC         1
1      Bob   Souris         2
2  Charlie  Clavier         1
3    Alice    Écran         2
4    David       PC         3
5     Emma   Casque         1
6      Bob    Écran         1
7    Lucas  Clavier         4

In [116]:
ventes

,id_commande,client,produit,quantite,prix_unitaire,date_commande,livree
0,1001,Alice,PC,1,999.99,1736467200000,True
1,1002,Bob,Souris,2,19.90,1736640000000,True
2,1003,Charlie,Clavier,1,49.90,1736899200000,False
3,1004,Alice,Écran,2,199.99,1737158400000,True
4,1005,David,PC,3,999.99,1737331200000,False
5,1006,Emma,Casque,1,79.90,1737417600000,True
6,1007,Bob,Écran,1,199.99,1737763200000,True
7,1008,Lucas,Clavier,4,49.90,1738022400000,False

In [118]:
ventes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_commande    8 non-null      int64
 1   client         8 non-null      object
 2   produit        8 non-null      object
 3   quantite       8 non-null      int64
 4   prix_unitaire  8 non-null      float64
 5   date_commande  8 non-null      int64
 6   livree         8 non-null      bool
dtypes: bool(1), float64(1), int64(3), object(2)
memory usage: 456.0+ bytes

In [133]:
ventes.select_dtypes(exclude = ["object", "bool"])

   id_commande  quantite  prix_unitaire  date_commande
0         1001         1         999.99  1736467200000
1         1002         2          19.90  1736640000000
2         1003         1          49.90  1736899200000
3         1004         2         199.99  1737158400000
4         1005         3         999.99  1737331200000
5         1006         1          79.90  1737417600000
6         1007         1         199.99  1737763200000
7         1008         4          49.90  1738022400000

In [127]:
ventes.select_dtypes('number')

   id_commande  quantite  prix_unitaire  date_commande
0         1001         1         999.99  1736467200000
1         1002         2          19.90  1736640000000
2         1003         1          49.90  1736899200000
3         1004         2         199.99  1737158400000
4         1005         3         999.99  1737331200000
5         1006         1          79.90  1737417600000
6         1007         1         199.99  1737763200000
7         1008         4          49.90  1738022400000

In [138]:
ventes.iloc[0]

id_commande               1001
client                   Alice
produit                     PC
quantite                     1
prix_unitaire           999.99
date_commande    1736467200000
livree                    True
Name: 0, dtype: object

In [4]:
ventes.iloc[2]

id_commande               1003
client                 Charlie
produit                Clavier
quantite                     1
prix_unitaire             49.9
date_commande    1736899200000
livree                   False
Name: 2, dtype: object

In [43]:
ventes.iloc[0:5]

,id_commande,client,produit,quantite,prix_unitaire,date_commande,livree
0,1001,Alice,PC,1,999.99,1736467200000,True
1,1002,Bob,Souris,2,19.90,1736640000000,True
2,1003,Charlie,Clavier,1,49.90,1736899200000,False
3,1004,Alice,Écran,2,199.99,1737158400000,True
4,1005,David,PC,3,999.99,1737331200000,False

In [34]:
ventes.tail(2)

   id_commande client  produit  quantite  prix_unitaire  date_commande  livree
6         1007    Bob    Écran         1         199.99  1737763200000    True
7         1008  Lucas  Clavier         4          49.90  1738022400000   False

In [44]:
ventes.loc[0, "client"]

'Alice'

In [45]:
ventes.loc[4, "produit"]

'PC'

In [50]:
ventes.loc[2, "prix_unitaire"]

np.float64(49.9)

In [63]:
ventes.id_commande=="1004"

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: id_commande, dtype: bool

In [68]:
ventes.at[0, "client"]

'Alice'

In [75]:
ventes[ventes["id_commande"] == 1004]

   id_commande client produit  quantite  prix_unitaire  date_commande  livree
3         1004  Alice   Écran         2         199.99  1737158400000    True

In [77]:
ventes.query("id_commande == 1004")

   id_commande client produit  quantite  prix_unitaire  date_commande  livree
3         1004  Alice   Écran         2         199.99  1737158400000    True

In [11]:
ventes.query("livree == True")

   id_commande client produit  quantite  prix_unitaire  date_commande  livree
0         1001  Alice      PC         1         999.99  1736467200000    True
1         1002    Bob  Souris         2          19.90  1736640000000    True
3         1004  Alice   Écran         2         199.99  1737158400000    True
5         1006   Emma  Casque         1          79.90  1737417600000    True
6         1007    Bob   Écran         1         199.99  1737763200000    True

In [18]:
ventes.query("livree != True")

,id_commande,client,produit,quantite,prix_unitaire,date_commande,livree
2,1003,Charlie,Clavier,1,49.90,1736899200000,False
4,1005,David,PC,3,999.99,1737331200000,False
7,1008,Lucas,Clavier,4,49.90,1738022400000,False

In [19]:
ventes.query("livree == False")

,id_commande,client,produit,quantite,prix_unitaire,date_commande,livree
2,1003,Charlie,Clavier,1,49.90,1736899200000,False
4,1005,David,PC,3,999.99,1737331200000,False
7,1008,Lucas,Clavier,4,49.90,1738022400000,False

In [20]:
ventes.query("prix_unitaire > 100")

   id_commande client produit  quantite  prix_unitaire  date_commande  livree
0         1001  Alice      PC         1         999.99  1736467200000    True
3         1004  Alice   Écran         2         199.99  1737158400000    True
4         1005  David      PC         3         999.99  1737331200000   False
6         1007    Bob   Écran         1         199.99  1737763200000    True

In [21]:
ventes.query("quantite > 1")

   id_commande client  produit  quantite  prix_unitaire  date_commande  livree
1         1002    Bob   Souris         2          19.90  1736640000000    True
3         1004  Alice    Écran         2         199.99  1737158400000    True
4         1005  David       PC         3         999.99  1737331200000   False
7         1008  Lucas  Clavier         4          49.90  1738022400000   False

In [26]:
ventes.query("client == 'Alice'")

   id_commande client produit  quantite  prix_unitaire  date_commande  livree
0         1001  Alice      PC         1         999.99  1736467200000    True
3         1004  Alice   Écran         2         199.99  1737158400000    True

In [28]:
ventes.query("produit == 'Écran'")

   id_commande client produit  quantite  prix_unitaire  date_commande  livree
3         1004  Alice   Écran         2         199.99  1737158400000    True
6         1007    Bob   Écran         1         199.99  1737763200000    True

In [30]:
ventes.query("client == 'Alice'").query("produit == 'Écran'")

   id_commande client produit  quantite  prix_unitaire  date_commande  livree
3         1004  Alice   Écran         2         199.99  1737158400000    True

In [31]:
ventes.query("50 < prix_unitaire < 500")

   id_commande client produit  quantite  prix_unitaire  date_commande  livree
3         1004  Alice   Écran         2         199.99  1737158400000    True
5         1006   Emma  Casque         1          79.90  1737417600000    True
6         1007    Bob   Écran         1         199.99  1737763200000    True

In [43]:
ventes.query("client == 'Alice' | client == 'Bob'")

   id_commande client produit  quantite  prix_unitaire  date_commande  livree
0         1001  Alice      PC         1         999.99  1736467200000    True
1         1002    Bob  Souris         2          19.90  1736640000000    True
3         1004  Alice   Écran         2         199.99  1737158400000    True
6         1007    Bob   Écran         1         199.99  1737763200000    True

In [34]:
ventes.sort_values("prix_unitaire")

,id_commande,client,produit,quantite,prix_unitaire,date_commande,livree
1,1002,Bob,Souris,2,19.90,1736640000000,True
2,1003,Charlie,Clavier,1,49.90,1736899200000,False
7,1008,Lucas,Clavier,4,49.90,1738022400000,False
5,1006,Emma,Casque,1,79.90,1737417600000,True
6,1007,Bob,Écran,1,199.99,1737763200000,True
3,1004,Alice,Écran,2,199.99,1737158400000,True
0,1001,Alice,PC,1,999.99,1736467200000,True
4,1005,David,PC,3,999.99,1737331200000,False

In [35]:
ventes.sort_values("prix_unitaire", ascending=False)

,id_commande,client,produit,quantite,prix_unitaire,date_commande,livree
0,1001,Alice,PC,1,999.99,1736467200000,True
4,1005,David,PC,3,999.99,1737331200000,False
6,1007,Bob,Écran,1,199.99,1737763200000,True
3,1004,Alice,Écran,2,199.99,1737158400000,True
5,1006,Emma,Casque,1,79.90,1737417600000,True
2,1003,Charlie,Clavier,1,49.90,1736899200000,False
7,1008,Lucas,Clavier,4,49.90,1738022400000,False
1,1002,Bob,Souris,2,19.90,1736640000000,True

In [36]:
ventes.sort_values("date_commande")

,id_commande,client,produit,quantite,prix_unitaire,date_commande,livree
0,1001,Alice,PC,1,999.99,1736467200000,True
1,1002,Bob,Souris,2,19.90,1736640000000,True
2,1003,Charlie,Clavier,1,49.90,1736899200000,False
3,1004,Alice,Écran,2,199.99,1737158400000,True
4,1005,David,PC,3,999.99,1737331200000,False
5,1006,Emma,Casque,1,79.90,1737417600000,True
6,1007,Bob,Écran,1,199.99,1737763200000,True
7,1008,Lucas,Clavier,4,49.90,1738022400000,False

In [41]:
ventes.sort_values(["client", "date_commande"])

,id_commande,client,produit,quantite,prix_unitaire,date_commande,livree
0,1001,Alice,PC,1,999.99,1736467200000,True
3,1004,Alice,Écran,2,199.99,1737158400000,True
1,1002,Bob,Souris,2,19.90,1736640000000,True
6,1007,Bob,Écran,1,199.99,1737763200000,True
2,1003,Charlie,Clavier,1,49.90,1736899200000,False
4,1005,David,PC,3,999.99,1737331200000,False
5,1006,Emma,Casque,1,79.90,1737417600000,True
7,1008,Lucas,Clavier,4,49.90,1738022400000,False

In [46]:
ventes.client.unique

<bound method Series.unique of 0      Alice
1        Bob
2    Charlie
3      Alice
4      David
5       Emma
6        Bob
7      Lucas
Name: client, dtype: object>

In [55]:
ventes.client.unique.value_counts()

AttributeError: 'function' object has no attribute 'value_counts'

In [54]:
ventes["produit"].value_counts()

produit
PC         2
Clavier    2
Écran      2
Souris     1
Casque     1
Name: count, dtype: int64