##### ---
# 🟢 PARTIE EXTRACT

In [1]:
import pandas as pd
clients = pd.read_csv("data/clients.csv")
commandes_Q1 = pd.read_csv("data/commandes_Q1.csv")
commandes_Q2 = pd.read_csv("data/commandes_Q2.csv")
produits = pd.read_csv("data/produits.csv")

In [2]:
clients.info()
clients.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 515 entries, 0 to 514
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         515 non-null    object
 1   nom               515 non-null    object
 2   email             484 non-null    object
 3   ville             515 non-null    object
 4   region            515 non-null    object
 5   segment           515 non-null    object
 6   date_inscription  515 non-null    object
 7   ca_historique     515 non-null    float64
 8   actif             515 non-null    bool
dtypes: bool(1), float64(1), object(7)
memory usage: 32.8+ KB

       ca_historique
count     515.000000
mean     7911.064311
std     14778.761524
min        40.170000
25%      1167.570000
50%      3130.240000
75%      7947.180000
max    155023.670000

In [3]:
commandes_Q1.info()
commandes_Q1.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3020 entries, 0 to 3019
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   commande_id       3020 non-null   object
 1   client_id         3020 non-null   object
 2   produit_id        3020 non-null   object
 3   quantite          3020 non-null   int64
 4   prix_unitaire     3020 non-null   float64
 5   montant_total     2964 non-null   float64
 6   date_commande     3020 non-null   object
 7   statut            2989 non-null   object
 8   mode_paiement     3020 non-null   object
 9   region_livraison  3020 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 236.1+ KB

          quantite  prix_unitaire  montant_total
count  3020.000000    3020.000000    2964.000000
mean      4.995695     128.106570     648.411113
std       2.583802     117.526057     738.756429
min       0.000000    -151.780000      10.760000
25%       3.000000      57.700000     209.295000
50%       5.000000      85.500000     419.120000
75%       7.000000     149.760000     760.635000
max       9.000000     793.250000    7139.250000

In [4]:
commandes_Q2.info()
commandes_Q2.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3220 entries, 0 to 3219
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   commande_id       3220 non-null   object
 1   client_id         3220 non-null   object
 2   produit_id        3220 non-null   object
 3   quantite          3220 non-null   int64
 4   prix_unitaire     3220 non-null   float64
 5   montant_total     3159 non-null   float64
 6   date_commande     3220 non-null   object
 7   statut            3189 non-null   object
 8   moyen_paiement    3220 non-null   object
 9   region_livraison  3220 non-null   object
 10  devise            3220 non-null   object
dtypes: float64(2), int64(1), object(8)
memory usage: 276.8+ KB

          quantite  prix_unitaire  montant_total
count  3220.000000    3220.000000    3159.000000
mean      4.927329     131.271230     656.876423
std       2.611954     123.640297     792.412006
min       0.000000    -793.250000      10.760000
25%       3.000000      57.700000     204.230000
50%       5.000000      85.500000     405.720000
75%       7.000000     151.780000     758.900000
max       9.000000     793.250000    7139.250000

In [5]:
produits.info()
produits.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   produit_id     152 non-null    object
 1   nom            152 non-null    object
 2   categorie      152 non-null    object
 3   prix_unitaire  152 non-null    float64
 4   stock          152 non-null    int64
 5   fournisseur    152 non-null    object
 6   actif          152 non-null    bool
dtypes: bool(1), float64(1), int64(1), object(4)
memory usage: 7.4+ KB

       prix_unitaire       stock
count     152.000000  152.000000
mean      129.627237  254.065789
std       118.669345  134.398275
min        10.760000    0.000000
25%        57.895000  153.250000
50%        86.155000  254.500000
75%       150.265000  360.750000
max       793.250000  491.000000

### Ex E1 ⭐ — Explorer les sources
Affichez pour chaque DataFrame : shape, colonnes, dtypes, et les 3 premières lignes.

In [6]:
# TON CODE ICI
clients.shape

(515, 9)

In [7]:
clients.columns

Index(['client_id', 'nom', 'email', 'ville', 'region', 'segment',
       'date_inscription', 'ca_historique', 'actif'],
      dtype='object')

In [8]:
clients.dtypes

client_id            object
nom                  object
email                object
ville                object
region               object
segment              object
date_inscription     object
ca_historique       float64
actif                  bool
dtype: object

In [9]:
clients.head(3)

,client_id,nom,email,ville,region,segment,date_inscription,ca_historique,actif
0,CLI0001,Client_1,client1@email.fr,Toulouse,Auvergne-RA,Startup,2021-02-01,129.67,True
1,CLI0002,Client_2,client2@email.fr,Lyon,Nouvelle-Aquitaine,Particulier,2022-08-11,42431.54,False
2,CLI0003,Client_3,client3@email.fr,Nantes,Occitanie,PME,2023-11-17,6895.77,True

In [10]:
commandes_Q1.shape

(3020, 10)

In [11]:
commandes_Q1.columns

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'mode_paiement',
       'region_livraison'],
      dtype='object')

In [12]:
commandes_Q1.dtypes

commande_id          object
client_id            object
produit_id           object
quantite              int64
prix_unitaire       float64
montant_total       float64
date_commande        object
statut               object
mode_paiement        object
region_livraison     object
dtype: object

In [13]:
commandes_Q1.head(3)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine

In [14]:
commandes_Q2.shape

(3220, 11)

In [15]:
commandes_Q2.columns

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'moyen_paiement',
       'region_livraison', 'devise'],
      dtype='object')

In [16]:
commandes_Q2.dtypes

commande_id          object
client_id            object
produit_id           object
quantite              int64
prix_unitaire       float64
montant_total       float64
date_commande        object
statut               object
moyen_paiement       object
region_livraison     object
devise               object
dtype: object

In [17]:
commandes_Q2.head(3)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,moyen_paiement,region_livraison,devise
0,CMD-Q2-00001,CLI0122,PRD0041,5,48.15,240.75,2024-05-14,retournée,CB,Auvergne-RA,EUR
1,CMD-Q2-00002,CLI0346,PRD0106,1,52.42,52.42,2024-04-18,livrée,CB,PACA,EUR
2,CMD-Q2-00003,CLI0282,PRD0021,8,78.18,625.44,2024-05-05,annulée,CB,Occitanie,EUR

In [18]:
produits.shape

(152, 7)

In [19]:
produits.columns

Index(['produit_id', 'nom', 'categorie', 'prix_unitaire', 'stock',
       'fournisseur', 'actif'],
      dtype='object')

In [20]:
produits.dtypes

produit_id        object
nom               object
categorie         object
prix_unitaire    float64
stock              int64
fournisseur       object
actif               bool
dtype: object

In [21]:
produits.head(3)

,produit_id,nom,categorie,prix_unitaire,stock,fournisseur,actif
0,PRD0001,Produit_Inf_1,Informatique,57.96,71,TechPro,True
1,PRD0002,Produit_Inf_2,Informatique,135.96,102,MediaShop,True
2,PRD0003,Produit_Inf_3,Informatique,83.45,372,ElecPlus,False

In [22]:
def inspecter(df, nom="DataFrame"):
    print(f"=== {nom} ===")
    print(f"shape : {df.shape}")
    print(df.columns)
    print(df.dtypes)
    display(df.head(3))

In [23]:
inspecter(produits, "produits")

=== produits ===
shape : (152, 7)
Index(['produit_id', 'nom', 'categorie', 'prix_unitaire', 'stock',
       'fournisseur', 'actif'],
      dtype='object')
produit_id        object
nom               object
categorie         object
prix_unitaire    float64
stock              int64
fournisseur       object
actif               bool
dtype: object

,produit_id,nom,categorie,prix_unitaire,stock,fournisseur,actif
0,PRD0001,Produit_Inf_1,Informatique,57.96,71,TechPro,True
1,PRD0002,Produit_Inf_2,Informatique,135.96,102,MediaShop,True
2,PRD0003,Produit_Inf_3,Informatique,83.45,372,ElecPlus,False

In [24]:
dataframes = {"clients": clients, "commandes_Q1": commandes_Q1, "commandes_Q2": commandes_Q2, "produits": produits}

In [25]:
for nom, df in dataframes.items():
    inspecter(df, nom)

=== clients ===
shape : (515, 9)
Index(['client_id', 'nom', 'email', 'ville', 'region', 'segment',
       'date_inscription', 'ca_historique', 'actif'],
      dtype='object')
client_id            object
nom                  object
email                object
ville                object
region               object
segment              object
date_inscription     object
ca_historique       float64
actif                  bool
dtype: object

,client_id,nom,email,ville,region,segment,date_inscription,ca_historique,actif
0,CLI0001,Client_1,client1@email.fr,Toulouse,Auvergne-RA,Startup,2021-02-01,129.67,True
1,CLI0002,Client_2,client2@email.fr,Lyon,Nouvelle-Aquitaine,Particulier,2022-08-11,42431.54,False
2,CLI0003,Client_3,client3@email.fr,Nantes,Occitanie,PME,2023-11-17,6895.77,True

=== commandes_Q1 ===
shape : (3020, 10)
Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'mode_paiement',
       'region_livraison'],
      dtype='object')
commande_id          object
client_id            object
produit_id           object
quantite              int64
prix_unitaire       float64
montant_total       float64
date_commande        object
statut               object
mode_paiement        object
region_livraison     object
dtype: object

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine

=== commandes_Q2 ===
shape : (3220, 11)
Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'moyen_paiement',
       'region_livraison', 'devise'],
      dtype='object')
commande_id          object
client_id            object
produit_id           object
quantite              int64
prix_unitaire       float64
montant_total       float64
date_commande        object
statut               object
moyen_paiement       object
region_livraison     object
devise               object
dtype: object

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,moyen_paiement,region_livraison,devise
0,CMD-Q2-00001,CLI0122,PRD0041,5,48.15,240.75,2024-05-14,retournée,CB,Auvergne-RA,EUR
1,CMD-Q2-00002,CLI0346,PRD0106,1,52.42,52.42,2024-04-18,livrée,CB,PACA,EUR
2,CMD-Q2-00003,CLI0282,PRD0021,8,78.18,625.44,2024-05-05,annulée,CB,Occitanie,EUR

=== produits ===
shape : (152, 7)
Index(['produit_id', 'nom', 'categorie', 'prix_unitaire', 'stock',
       'fournisseur', 'actif'],
      dtype='object')
produit_id        object
nom               object
categorie         object
prix_unitaire    float64
stock              int64
fournisseur       object
actif               bool
dtype: object

,produit_id,nom,categorie,prix_unitaire,stock,fournisseur,actif
0,PRD0001,Produit_Inf_1,Informatique,57.96,71,TechPro,True
1,PRD0002,Produit_Inf_2,Informatique,135.96,102,MediaShop,True
2,PRD0003,Produit_Inf_3,Informatique,83.45,372,ElecPlus,False

### Ex E2 ⭐ — Détecter les différences entre Q1 et Q2
Trouvez les colonnes présentes dans Q2 mais absentes de Q1, et vice-versa.
Affichez les différences clairement.

In [26]:
commandes_Q1.columns

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'mode_paiement',
       'region_livraison'],
      dtype='object')

In [27]:
commandes_Q2.columns

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'moyen_paiement',
       'region_livraison', 'devise'],
      dtype='object')

In [28]:
print(commandes_Q1.columns.difference(commandes_Q2.columns))

Index(['mode_paiement'], dtype='object')

In [29]:
print(commandes_Q2.columns.difference(commandes_Q1.columns))

Index(['devise', 'moyen_paiement'], dtype='object')

### Ex E3 ⭐ — Harmoniser les colonnes
1. Renommez la colonne problématique dans Q2 pour qu'elle corresponde à Q1
2. Ajoutez la colonne manquante dans Q1 avec une valeur par défaut
3. Vérifiez que les deux DataFrames ont maintenant les mêmes colonnes

In [30]:
# TON CODE ICI
commandes_Q2 = commandes_Q2.rename(columns={"moyen_paiement" : "mode_paiement"})
commandes_Q1["devise"] = "EUR"
display(commandes_Q1.head(1))
display(commandes_Q2.head(1))
set(commandes_Q1.columns) == set(commandes_Q2.columns)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise
0,CMD-Q2-00001,CLI0122,PRD0041,5,48.15,240.75,2024-05-14,retournée,CB,Auvergne-RA,EUR

True

### Ex E4 ⭐ — Consolider avec pd.concat
1. Ajoutez une colonne `source` dans Q1 (`'Q1_2024'`) et Q2 (`'Q2_2024'`)
2. Concaténez Q1 et Q2 avec `pd.concat`
3. Vérifiez que le total de lignes est cohérent
4. Affichez la répartition des lignes par source

In [31]:
# TON CODE ICI
commandes_Q1["source"] = "Q1_2024"
commandes_Q2["source"] = "Q2_2024"
display(commandes_Q1.head(1), commandes_Q2.head(1))
commandes = pd.concat([commandes_Q1, commandes_Q2], ignore_index=True)
display(commandes.head(1), commandes.tail(1))
print("Q1=",len(commandes_Q1), " Q2=",len(commandes_Q2), " commandes=",len(commandes), end=(""))
commandes["source"].value_counts(sort=False)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR,Q1_2024

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source
0,CMD-Q2-00001,CLI0122,PRD0041,5,48.15,240.75,2024-05-14,retournée,CB,Auvergne-RA,EUR,Q2_2024

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR,Q1_2024

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source
6239,CMD-Q2-03170,CLI0122,PRD0120,5,107.93,539.65,2024-04-02,livrée,PayPal,Nouvelle-Aquitaine,EUR,Q2_2024

Q1= 3020  Q2= 3220  commandes= 6240

source
Q1_2024    3020
Q2_2024    3220
Name: count, dtype: int64

### Ex E5 ⭐⭐ — Fonction extract()
Encapsulez tout dans une fonction `extract(q1_path, q2_path, clients_path, produits_path) -> dict`
qui retourne un dictionnaire avec les 4 DataFrames harmonisés et consolidés.
La fonction doit afficher des logs à chaque étape.

In [32]:
# TON CODE ICI
def extract(q1_path, q2_path, clients_path, produit_path):
    print("chargement des dataframes ...")
    commandes_Q1 = pd.read_csv(q1_path)
    commandes_Q2 = pd.read_csv(q2_path)
    clients = pd.read_csv(clients_path)
    produits = pd.read_csv(produit_path)
    dataframes = [commandes_Q1, commandes_Q2, clients, produits]
    for df in dataframes:
        display(pd.concat([df.head(2), df.tail(2)]))
    commandes_Q2 = commandes_Q2.rename(columns={"moyen_paiement" : "mode_paiement"})
    commandes_Q1["devise"] = "EUR"
    commandes_Q1["source"] = "Q1_2024"
    commandes_Q2["source"] = "Q2_2024"
    commandes = pd.concat([commandes_Q1, commandes_Q2], ignore_index=True)
    print("DataFrames harmonisés et consolidés")
    dataframes = [commandes, clients, produits]
    for df in dataframes:
        display(pd.concat([df.head(2), df.tail(2)]))

extract("data/commandes_Q1.csv", "data/commandes_Q2.csv", "data/clients.csv", "data/produits.csv")

chargement des dataframes ...

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie
3018,CMD-Q1-02488,CLI0093,PRD0036,3,211.79,635.37,2024-02-18,livrée,CB,Nouvelle-Aquitaine
3019,CMD-Q1-01522,CLI0275,PRD0024,6,20.71,124.26,2024-02-15,livrée,PayPal,Île-de-France

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,moyen_paiement,region_livraison,devise
0,CMD-Q2-00001,CLI0122,PRD0041,5,48.15,240.75,2024-05-14,retournée,CB,Auvergne-RA,EUR
1,CMD-Q2-00002,CLI0346,PRD0106,1,52.42,52.42,2024-04-18,livrée,CB,PACA,EUR
3218,CMD-Q2-02836,CLI0085,PRD0126,1,82.76,82.76,2024-05-14,livrée,CB,Occitanie,EUR
3219,CMD-Q2-03170,CLI0122,PRD0120,5,107.93,539.65,2024-04-02,livrée,PayPal,Nouvelle-Aquitaine,EUR

,client_id,nom,email,ville,region,segment,date_inscription,ca_historique,actif
0,CLI0001,Client_1,client1@email.fr,Toulouse,Auvergne-RA,Startup,2021-02-01,129.67,True
1,CLI0002,Client_2,client2@email.fr,Lyon,Nouvelle-Aquitaine,Particulier,2022-08-11,42431.54,False
513,CLI0033,Client_33,client33@email.fr,Nantes,PACA,Startup,2020-12-02,10689.65,True
514,CLI0163,Client_163,client163@email.fr,Nantes,Nouvelle-Aquitaine,PME,2023-02-04,10621.32,True

,produit_id,nom,categorie,prix_unitaire,stock,fournisseur,actif
0,PRD0001,Produit_Inf_1,Informatique,57.96,71,TechPro,True
1,PRD0002,Produit_Inf_2,Informatique,135.96,102,MediaShop,True
150,PRD0151,Produit_Rés_151,Réseau,221.15,468,ElecPlus,True
151,PRD0152,Produit_Rés_152,Réseau,499.98,150,ElecPlus,True

DataFrames harmonisés et consolidés

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR,Q1_2024
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie,EUR,Q1_2024
6238,CMD-Q2-02836,CLI0085,PRD0126,1,82.76,82.76,2024-05-14,livrée,CB,Occitanie,EUR,Q2_2024
6239,CMD-Q2-03170,CLI0122,PRD0120,5,107.93,539.65,2024-04-02,livrée,PayPal,Nouvelle-Aquitaine,EUR,Q2_2024

,client_id,nom,email,ville,region,segment,date_inscription,ca_historique,actif
0,CLI0001,Client_1,client1@email.fr,Toulouse,Auvergne-RA,Startup,2021-02-01,129.67,True
1,CLI0002,Client_2,client2@email.fr,Lyon,Nouvelle-Aquitaine,Particulier,2022-08-11,42431.54,False
513,CLI0033,Client_33,client33@email.fr,Nantes,PACA,Startup,2020-12-02,10689.65,True
514,CLI0163,Client_163,client163@email.fr,Nantes,Nouvelle-Aquitaine,PME,2023-02-04,10621.32,True

,produit_id,nom,categorie,prix_unitaire,stock,fournisseur,actif
0,PRD0001,Produit_Inf_1,Informatique,57.96,71,TechPro,True
1,PRD0002,Produit_Inf_2,Informatique,135.96,102,MediaShop,True
150,PRD0151,Produit_Rés_151,Réseau,221.15,468,ElecPlus,True
151,PRD0152,Produit_Rés_152,Réseau,499.98,150,ElecPlus,True

---
# 🟡 PARTIE TRANSFORM

### Ex T1 ⭐ — Audit initial
Écris une fonction `audit_dataframe(df, nom)` qui affiche :
- Shape
- Nombre de NaN total et par colonne (en %)
- Nombre de doublons
- Types de chaque colonne

In [33]:
# TON CODE ICI
def audit_dataframe(df, nom):
    print(f"==={nom}===")
    print(f"shape: {df.shape[0]} lignes x {df.shape[1]} colonnes")
    print(f"nombre total de NaN: {df.isna().sum().sum()}")
    print("\n---pourcentage de NaN par colonne---")
    print(df.isna().sum() / len(df) * 100)
    print(f"\ndoublons: {df.duplicated().sum()}")
    print("\n---Types---")
    print(df.dtypes)

In [34]:
audit_dataframe(clients, "clients")

===clients===
shape: 515 lignes x 9 colonnes
nombre total de NaN: 31

---pourcentage de NaN par colonne---
client_id           0.000000
nom                 0.000000
email               6.019417
ville               0.000000
region              0.000000
segment             0.000000
date_inscription    0.000000
ca_historique       0.000000
actif               0.000000
dtype: float64

doublons: 15

---Types---
client_id            object
nom                  object
email                object
ville                object
region               object
segment              object
date_inscription     object
ca_historique       float64
actif                  bool
dtype: object

### Ex T2 ⭐ — Supprimer les doublons
Sur le DataFrame consolidé :
1. Détectez et affichez le nombre de doublons
2. Montrez 3 exemples de lignes dupliquées
3. Supprimez les doublons (gardez la première occurrence)
4. Vérifiez qu'il n'en reste plus

In [35]:
# TON CODE ICI
print("nombre de doublons: ", commandes.duplicated().sum().sum())
print("les 3 premier doublons:")
display(commandes[commandes.duplicated()].head(3))
commandes_sans_doublon = commandes.drop_duplicates()
print("commandes sans doublons")
display(commandes_sans_doublon[commandes_sans_doublon.duplicated()].head(3))

nombre de doublons:  40
les 3 premier doublons:

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source
3000,CMD-Q1-02950,CLI0271,PRD0124,2,55.52,111.04,2024-02-27,annulée,CB,Île-de-France,EUR,Q1_2024
3001,CMD-Q1-00072,CLI0001,PRD0027,7,45.84,320.88,2024-03-20,en_cours,CB,Île-de-France,EUR,Q1_2024
3002,CMD-Q1-00145,CLI0441,PRD0020,9,304.72,2742.48,2024-02-19,livrée,CB,Île-de-France,EUR,Q1_2024

commandes sans doublons

Empty DataFrame
Columns: [commande_id, client_id, produit_id, quantite, prix_unitaire, montant_total, date_commande, statut, mode_paiement, region_livraison, devise, source]
Index: []

### Ex T3 ⭐ — Corriger les types
1. Convertissez `date_commande` en datetime en gérant les formats incohérents
2. Extrayez : `annee`, `mois`, `trimestre`, `jour_semaine`
3. Convertissez `quantite` en numérique avec gestion des erreurs
4. Affichez les types avant et après

In [36]:
# TON CODE ICI
commandes_sans_doublon["date_commande"] = pd.to_datetime(commandes_sans_doublon

_IncompleteInputError: incomplete input (3218360678.py, line 2)

In [ ]:
print(pd.to_datetime(commandes_sans_doublon["date_commande"], errors="coerce", format="mixed"))
aaa=pd.to_datetime(commandes_sans_doublon["date_commande"], errors="coerce", format="mixed")
aaa.isna().sum()
b = aaa.to_frame()
commandes_sans_doublon["date_commande"]=b

In [ ]:
b = aaa.to_frame()
type(b)

In [ ]:
type(commandes_sans_doublon["date_commande"].loc[0])
commandes_sans_doublon["date_commande"].isna().sum()

In [ ]:
# TON CODE ICI
commandes_sans_doublon["annee"] = commandes_sans_doublon["date_commande"].dt.year
commandes_sans_doublon["mois"] = commandes_sans_doublon["date_commande"].dt.month
commandes_sans_doublon["trimestre"] = commandes_sans_doublon["date_commande"].dt.quarter
commandes_sans_doublon["jour_semaine"] = commandes_sans_doublon["date_commande"].dt.weekday
commandes_sans_doublon.head(3)

In [ ]:
type(commandes_sans_doublon["quantite"].loc[0])
commandes_sans_doublon.dtypes
commandes_sans_doublon["quantite"].isna().sum()

ex T4 traiter les NaN

In [ ]:
commandes_sans_doublon["montant_total"].isna().sum()

In [ ]:
isna = commandes_sans_doublon["montant_total"].isna()

for index in isna.keys():
    if isna.loc[index]:
        commandes_sans_doublon.loc[index, "montant_total"] = commandes_sans_doublon.loc[index, "quantite"] * commandes_sans_doublon.loc[index, "prix_unitaire"]

In [ ]:
commandes_sans_doublon.statut.isna().sum()

In [ ]:
isna = commandes_sans_doublon.statut.isna()

for index in isna.keys():
    if isna.loc[index]:
        commandes_sans_doublon.loc[index, "statut"] = "inconnu"

In [ ]:
commandes_sans_doublon.statut.isna().sum()

In [ ]:
commandes_sans_doublon.date_commande.isna().sum()

### Ex T5 ⭐⭐ — Détecter et traiter les aberrants
1. Détectez les prix négatifs → supprimez ces lignes
2. Détectez les quantités nulles ou négatives → supprimez
3. Vérifiez la cohérence `montant_total = quantite × prix_unitaire` → corrigez les incohérences
4. Affichez un résumé des corrections effectuées

In [38]:
# TON CODE ICI
keys = (commandes_sans_doublon.prix_unitaire < 0).keys()
keys
#commandes_sans_doublon.drop(keys, inplace=True)

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       6210, 6211, 6212, 6213, 6214, 6215, 6216, 6217, 6218, 6219],
      dtype='int64', length=6200)

In [44]:
index = commandes_sans_doublon[commandes_sans_doublon["prix_unitaire"] < 0].index
commandes_sans_doublon.drop(index, inplace=True)

/tmp/ipykernel_13101/1568214468.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  commandes_sans_doublon.drop(index, inplace=True)

In [45]:
len(commandes_sans_doublon)

6178

In [46]:
(commandes_sans_doublon.prix_unitaire < 0).sum()

np.int64(0)

In [50]:
index = (commandes_sans_doublon[commandes_sans_doublon["quantite"]*commandes_sans_doublon["prix_unitaire"]!=commandes_sans_doublon["montant_total"]]).index

In [49]:
for i in index:
    commandes_sans_doublon.loc[i, "montant_total"] = commandes_sans_doublon.loc[i, "prix_unitaire"] * commandes_sans_doublon.loc[i, "quantite"]

In [52]:
commandes_sans_doublon.shape

(6178, 12)

### Ex T6 ⭐⭐ — Jointures avec les référentiels
1. Nettoyez `df_clients` (doublons sur `client_id`)
2. Filtrez `df_produits` pour ne garder que les produits actifs
3. Faites un LEFT JOIN commandes ← clients (colonnes : ville, region, segment)
4. Faites un LEFT JOIN commandes ← produits (colonnes : nom, categorie, fournisseur)
5. Vérifiez le nombre de lignes avant et après (doit être identique avec LEFT JOIN)

In [58]:
# TON CODE ICI
clients.drop_duplicates(subset=["client_id"], inplace=True)

In [59]:
len(clients)

500

In [62]:
clients_filtre = clients[["client_id", "ville", "region", "segment"]]

In [63]:
commandes_sans_doublon.merge(clients_filtre, on="client_id", how="left")

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source,ville,region,segment
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR,Q1_2024,Marseille,PACA,Particulier
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie,EUR,Q1_2024,Nantes,Nouvelle-Aquitaine,Startup
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine,EUR,Q1_2024,Nantes,PACA,Particulier
3,CMD-Q1-00004,CLI0381,PRD0061,8,75.83,606.64,2024-01-17,annulée,PayPal,PACA,EUR,Q1_2024,Lyon,Auvergne-RA,Particulier
4,CMD-Q1-00005,CLI0187,PRD0040,4,71.91,287.64,2024-03-20,en_cours,CB,Occitanie,EUR,Q1_2024,Montpellier,Île-de-France,Particulier
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6173,CMD-Q2-03196,CLI0454,PRD0127,1,63.31,63.31,2024-06-09,livrée,PayPal,Auvergne-RA,EUR,Q2_2024,Paris,Auvergne-RA,Startup
6174,CMD-Q2-03197,CLI0222,PRD0054,5,124.37,621.85,2024-06-10,livrée,PayPal,Nouvelle-Aquitaine,EUR,Q2_2024,Toulouse,Nouvelle-Aquitaine,PME
6175,CMD-Q2-03198,CLI0030,PRD0135,3,112.71,338.13,2024-05-06,livrée,CB,Nouvelle-Aquitaine,EUR,Q2_2024,Nice,PACA,Grand Compte
6176,CMD-Q2-03199,CLI0187,PRD0091,7,75.28,526.96,2024-05-21,livrée,CB,Nouvelle-Aquitaine,EUR,Q2_2024,Montpellier,Île-de-France,Particulier
6177,CMD-Q2-03200,CLI0434,PRD0059,8,117.97,943.76,2024-06-25,livrée,CB,PACA,EUR,Q2_2024,Lyon,Nouvelle-Aquitaine,Particulier

### Ex T7 ⭐⭐ — Feature Engineering
Créez les colonnes suivantes :
1. `tranche_montant` : `<100€` / `100-500€` / `500-2000€` / `>2000€` avec `pd.cut()`
2. `saison` : depuis le mois (Hiver/Printemps/Été/Automne)
3. `est_annulee` : booléen True si statut == 'annulée'
4. `ca_perdu` : montant_total si commande annulée, sinon 0
5. `delai_inscription_commande` : nb de jours entre date_inscription du client et date_commande

Affichez `value_counts()` pour les colonnes catégorielles créées.

In [ ]:
# TON CODE ICI

### Ex T8 ⭐⭐⭐ — Validation qualité
Écris une fonction `valider_pipeline(df) -> bool` qui :
1. Vérifie qu'il n'y a plus de NaN sur les colonnes critiques
2. Vérifie qu'il n'y a plus de doublons
3. Vérifie que tous les prix sont > 0
4. Vérifie que toutes les quantités sont > 0
5. Vérifie que montant_total == quantite × prix_unitaire (à 1 centime près)
6. Retourne True si tout est OK, False sinon avec les erreurs détaillées

In [ ]:
# TON CODE ICI

### Ex T9 ⭐⭐⭐ — Analyse métier post-transform
Maintenant que les données sont propres, répondez en code :
1. Quel est le CA total du S1 2024 ?
2. Quel trimestre a le CA le plus élevé ?
3. Quelle région génère le plus de CA ?
4. Quel segment client est le plus rentable ?
5. Quelle catégorie de produit a le taux d'annulation le plus élevé ?
6. Quel est le CA perdu sur les annulations ?

In [ ]:
# TON CODE ICI

---
# 🔵 PARTIE LOAD

### Ex L1 ⭐ — Export CSV
1. Exportez le DataFrame enrichi en CSV dans `../output/commandes_enrichies.csv`
2. Vérifiez la taille du fichier en Ko
3. Rechargez le CSV et vérifiez que le shape est identique

In [ ]:
# TON CODE ICI

### Ex L2 ⭐⭐ — Export Parquet
1. Exportez en Parquet dans `../output/commandes_S1.parquet`
2. Comparez la taille CSV vs Parquet
3. Rechargez le Parquet et vérifiez le shape
4. Mesurez le temps de lecture CSV vs Parquet avec `%%time`

In [ ]:
# TON CODE ICI

### Ex L3 ⭐⭐ — SQLite
1. Créez une base SQLite `../output/ecommerce.db`
2. Chargez le DataFrame dans une table `commandes`
3. Créez une deuxième table `reporting` avec un agrégat par trimestre et région
4. Exécutez au moins 3 requêtes SQL directement depuis Python et affichez les résultats

In [ ]:
# TON CODE ICI

### Ex L4 ⭐⭐⭐ — Parquet partitionné
Exportez le DataFrame en Parquet partitionné par `trimestre` et `region_livraison`.

Puis répondez :
- Combien de fichiers Parquet sont créés ?
- Quelle est la taille totale vs le Parquet non partitionné ?
- Quel est l'avantage du partitionnement pour PySpark ?

In [ ]:
# TON CODE ICI

---
# 🔴 PIPELINE COMPLET

### Ex P1 ⭐⭐ — Pipeline modulaire
Écris 3 fonctions séparées :
- `extract(data_dir) -> dict`
- `transform(sources: dict) -> pd.DataFrame`
- `load(df, output_dir) -> None`

Chacune doit avoir une docstring et des logs.
Teste chaque fonction indépendamment.

In [ ]:
# TON CODE ICI

### Ex P2 ⭐⭐⭐ — Pipeline avec gestion d'erreurs
Améliore ton pipeline avec :
1. `try/except` sur chaque étape critique
2. Un log d'erreur détaillé si une étape échoue
3. La pipeline ne doit pas crasher complètement si un fichier est manquant — elle doit logger l'erreur et continuer avec les autres

In [ ]:
# TON CODE ICI

### Ex P3 ⭐⭐⭐ — Tests unitaires du pipeline
Écris 5 tests pour ton pipeline :
1. `test_extract_retourne_4_sources()`
2. `test_transform_supprime_doublons()`
3. `test_transform_pas_de_prix_negatif()`
4. `test_transform_montant_coherent()`
5. `test_load_cree_les_fichiers()`

Chaque test affiche ✅ PASS ou ❌ FAIL.

In [ ]:
# TON CODE ICI

### Ex P4 ⭐⭐⭐⭐ — PROJET FINAL : Pipeline automatisé
Crée un pipeline complet qui :

1. **Détecte automatiquement** tous les fichiers CSV dans `../data_etl/` qui commencent par `commandes_`
2. **Les traite tous** sans avoir à spécifier les chemins manuellement
3. **Génère un rapport HTML** avec :
   - Les statistiques clés (CA, nb commandes, taux annulation)
   - 3 graphiques Plotly intégrés
4. **Sauvegarde** en CSV + Parquet + SQLite
5. **Loggue** chaque étape avec timestamps

C'est exactement ce que vous ferez en PySpark la semaine prochaine, mais à l'échelle de plusieurs To.

📎 Docs utiles :
- [glob — trouver des fichiers](https://docs.python.org/3/library/glob.html)
- [logging](https://docs.python.org/3/library/logging.html)
- [Plotly — export HTML](https://plotly.com/python/interactive-html-export/)

In [ ]:
# TON CODE ICI